version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mysql-php
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

